# -*- coding: utf-8 -*-
"""Vehicle_Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVurnqT1HCYstNoMq9GABw3GycitWDOS
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics
# import opencv module
import cv2
# Import YOLO class from ultralytics module 
from ultralytics import YOLO
# for displying the video inside jupyter notebook
from IPython.display import Video

# create model obhect from YOLO class
model = YOLO('yolov8n.pt')
# input video path for processing
VIDEO_PATH = "/content/drive/MyDrive/Edge_AI/Cars.mp4"
# output path for processed video 
OUTPUT_PATH = "/content/output_video.mp4"
# create cap object for object creation 
cap = cv2.VideoCapture(VIDEO_PATH)
# check for error while opening the video for classification
assert cap.isOpened(), "Error reading video file"
# functions for getting width , height and fps of frames
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)
#if fps is equivalent to zeor then by default take 25 
if fps <= 0:
    fps = 25.0
# configure output video generation
out = cv2.VideoWriter(
    OUTPUT_PATH,
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (w, h)
)
# start analysing the frames 
while cap.isOpened():
    success, frame = cap.read()
    if not success:
        break

    # Run detection
    results = model(frame)
    # if obhects are are detected for classification go inside loop
    if results[0].boxes is not None:
        boxes = results[0].boxes
        # extract the co-ordinates for object detected extaract class id and confidance score of each object 
        xyxy = boxes.xyxy.cpu().numpy()
        cls_ids = boxes.cls.cpu().numpy().astype(int)
        confs = boxes.conf.cpu().numpy()
      
        for box, cls_id, conf in zip(xyxy, cls_ids, confs):
            x1, y1, x2, y2 = map(int, box)

            class_name = model.names[cls_id]
            label = f"{class_name} {conf:.2f}"

            # Draw rectangle
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

            # Draw label
            cv2.putText(
                frame,
                label,
                (x1, y1 - 10),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                (0, 255, 255),
                2
            )

    out.write(frame)

cap.release()
out.release()

print("Done!")
